### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by live627** [live627/pikaday#1]
### Merged PRs
- #929
- #930
- #918
- #907
- #905
- #904
- #833
- #807
- #703
- #658
- #620
- #601
- #581
- #572
- #525
- #506
- #439
- #397
- #394
- #387
- #341
- #330
- #308

#### Look into
 - [ ] #756 (fixes #582 and #723)
 - [ ] #751
 - [ ] #717
 - [ ] #325

### Issues fixed
- #773 (from #833)
- #806 (from #807)
- #662 (from #703)
- #588 (from #439)
- #569 (from #397)
- #305 (from #394)
- #321 (from #330)
- https://github.com/Pikaday/Pikaday/issues/815
- #910 (duplicate of #149)

**Comment by martinbarilik** [comment]
Status on this to be finally merged into master ?

**Comment by live627** [comment]
the upstream master?

**Comment by martinbarilik** [comment]
What i meant to ask is when are PRs going to get into master branch ( to be released in new version )

**Comment by live627** [comment]
But which repository?

**Comment by martinbarilik** [comment]
I am deeply sorry, i thougth i was at [Pikaday](https://github.com/Pikaday/Pikaday).

**Comment by live627** [comment]
I'm not a maintainer there.  I created this fork for my own use and because
nothing has been going on there.
